server:
  port: 8080

---

spring:
  profiles: default
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  cloud:
    stream:
      kafka:
        binder:
          brokers: my-kafka.default.svc.cluster.local:9092
        streams:
          binder:
            configuration:
              default:
                key:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
                value:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
      bindings:
        event-in:
          group: viewpage
          destination: socar
          contentType: application/json
        event-out:
          destination: socar
          contentType: application/json

logging:
  level:
    org.hibernate.type: trace
    org.springframework.cloud: debug
server:
  port: 8085
---

spring:
  application:
    name: viewpage
  profiles: docker
  sleuth:
    propagation-keys: x-request-id,x-ot-span-context
    propagation:
      type: B3,W3C
  opentracing:
    enabled: true
  zipkin:
    base-url: http://zipkin.istio-system:9411
  cloud:
    stream:
      kafka:
        binder:
          brokers: my-kafka.default.svc.cluster.local:9092
        streams:
          binder:
            configuration:
              default:
                key:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
                value:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
      bindings:
        event-in:
          group: viewpage
          destination: socar
          contentType: application/json
        event-out:
          destination: socar
          contentType: application/json